  version: '3.1'
  services:
    postgresql:
      image: postgres
      ports:
        - '5432:5432'
      volumes:
        - ./data:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=13032022
        - POSTGRES_USER=ann
        - POSTGRES_DB=my_super_db
